language: python
branches:
  only:
  - master
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install ghp-import
script:
- python -m pelican content
- ghp-import -n output
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master