language: python
branches:
  only:
  - master
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install ghp-import
script:
- git submodule update --init --recursive
after_deploy:
- ghp-import -p -n output
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: akbNex+bjL+Ks2vUFI9X+2FAOvHhfyHuEsBmztuReQmlZiZB5AC/ElSq2rVPvv4dW4RWNQkQd4jjzdtBihv64yw44Iddyn3kuGnOa2dQGMbKlTZ0tU1TZMTW4L/8a8MdwUI6nyUxZwKhqHE+CD8aJ47hpUNNy+O6UCs2lzsMaXiktU56DTP/zxIwqaIPjFuUL2rAMANo4Nx4uhK4dxR53AfGqMV4GLVrcEviZHUpALih0jr888mGznkoqyf+tzweUBvUK9tJ0wEvv9iciTVtmVxngx/u3kEbzuDt+qGi/tcSlfaKGbU0rDzHrt8vvuQZkhzhavEoGKcSwul5pB59jQdQI2g633b9Fex7WdOTzqUs8xG3G2KWahuv4zdXbMcmVpXYCbgzsDjN5EXIV9KofIW1bagdVp0+04PXLwe7ak/6Lj4qUafhyFKyKcWGyB+xN3W2rRf5CxNrJuJj1zVVll29Wgcg69UUpRs6cx4ZIyrvMDdTNo6P+lfv41BJQToC8F6t7zxFWkebjTBmE9AZbimvqpRXFZRzmGQJvlX2ne6vnG8oIBb9C9I8J/6eY9wms1Tskn1jkIjFlRIwlPLggYV5Ql7pccrPs8pl46IS91YPsUD9NQ57UDTLatdn5/WHjIGJUvZX/UT7hAhJCU/kGj7gNi5hnXmUIsi9fv77x6E=
